/'
Ferramenta:     sudo apt install plantuml
Para executar:  plantuml -tpdf arquivo.puml
Online:         https://www.planttext.com
'/
@startuml
title Instanciação e incorporação de um agente em JACAMOb

actor Designer
participant JaCaMo
participant NECK
participant Jason
participant JaCa

participant Moise
participant ORA4MAS
participant CArtAgO


participant NPL

activate JaCaMo




group Iniciando Organização
JaCaMo -> Moise : Moise.start()
activate Moise
Moise -> ORA4MAS : start()
activate ORA4MAS
ORA4MAS -> CArtAgO : OrgBoard.init()
activate CArtAgO
CArtAgO -> CArtAgO :Workspace.createWorkspace()
CArtAgO -> CArtAgO :Workspace.init()
CArtAgO -> CArtAgO :Workspace.makeArtifact()
CArtAgO --> ORA4MAS
deactivate CArtAgO
ORA4MAS --> Moise
deactivate ORA4MAS

Moise -> CArtAgO : MoiseElement.init()
activate CArtAgO
CArtAgO -> CArtAgO : ObsProperty.init()
CArtAgO --> Moise
deactivate CArtAgO
Moise --> JaCaMo
deactivate Moise

JaCaMo -> Moise : Moise.createScheme()
activate Moise
Moise -> ORA4MAS : createScheme()
activate ORA4MAS
ORA4MAS -> CArtAgO : OrgBoard.createScheme()
activate CArtAgO
CArtAgO -> CArtAgO : Workspace.makeArtifact()
CArtAgO --> ORA4MAS
deactivate CArtAgO
ORA4MAS -> ORA4MAS : SchemeBoard.init()
ORA4MAS --> Moise 
deactivate ORA4MAS

Moise -> CArtAgO : MoiseElement.init()
activate CArtAgO
CArtAgO -> NPL : ObsProperty.init()
activate NPL
NPL -> NPL : init()
NPL -> NPL : deontic_operator()
NPL --> CArtAgO
deactivate NPL
CArtAgO --> Moise
deactivate CArtAgO
Moise --> JaCaMo
deactivate Moise
JaCaMo -> Moise : Moise.createGroup()
activate Moise
Moise -> ORA4MAS : createGroup()
activate ORA4MAS
ORA4MAS -> CArtAgO : OrgBoard.createGroup()
activate CArtAgO
CArtAgO -> CArtAgO : Workspace.makeArtifact()
CArtAgO --> ORA4MAS
deactivate CArtAgO
ORA4MAS -> ORA4MAS : GroupBoard.init()
ORA4MAS --> Moise
deactivate ORA4MAS
Moise -> CArtAgO : MoiseElement.init()
activate CArtAgO
CArtAgO -> NPL : ObsProperty.init()
activate NPL
NPL -> NPL : init()
NPL -> NPL : deontic_operator()
NPL --> CArtAgO
deactivate NPL
CArtAgO --> Moise
deactivate CArtAgO
Moise --> JaCaMo
deactivate Moise
end

group Iniciando o Ambiente
JaCaMo -> CArtAgO : Cartago.start()
activate CArtAgO
CArtAgO -> CArtAgO : Workspace.createWorkspace()
CArtAgO -> CArtAgO : Workspace.init()
CArtAgO -> CArtAgO : Workspace.makeArtifact()
CArtAgO -> CArtAgO : ObsProperty.init()
CArtAgO --> JaCaMo
deactivate CArtAgO
end

group Iniciando Dimensão dos Agentes
JaCaMo -> Jason : JaCaMoLauncher.startAgs()
activate Jason
Jason -> Jason : RunLocalMAS.startAgs()
Jason -> Jason : RunLocalMAS.createAgsThreads()
Jason -> Jason : LocalAgArch.startThread()
Jason -> JaCaMo : TransitionSystem.sense()
activate JaCaMo
JaCaMo -> NECK : JaCaMoAgArch.perceive()

activate NECK
NECK -> NECK : Body.sense()
NECK ->  NECK : Apparatus.loadDesires()
NECK ->  NECK : Apparatus.loadPercepts()


NECK ->  Jason : Body:updatePercepts()
activate Jason
Jason -> Jason : BeliefBase.add()
Jason -> Jason : Circumstace.addEvent()
Jason --> NECK
deactivate Jason

NECK -> Jason : Body.updateDesires()
activate Jason
Jason -> Jason : GoalListener.goalStarted()
Jason --> NECK
deactivate Jason
NECK --> JaCaMo
deactivate JaCaMo
JaCaMo --> Jason

activate Jason
Jason -> Jason: AgArch.checkMail()



end


deactivate JaCaMo

@enduml
